import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { ReduxProvider } from "../provider";
import "../styles/AIAssistantChat.css";
import { CartProvider } from "@/context/CartContext";
import GlobalAIChat from "./(components)/GlobalAIChat";
import { FavouriteProvider } from "@/context/FavouriteContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Field Finder",
  description: "Generated by MT",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <CartProvider>
            <FavouriteProvider>
              {children}
              <GlobalAIChat />
              <ToastContainer
                position="top-right"
                autoClose={2000}
                theme="colored"
              />
            </FavouriteProvider>
          </CartProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
